export const ADD_OBJECT = 'ADD_OBJECT';
export const DELETE_OBJECT = 'DELETE_OBJECT';
export const UPDATE_OBJECT = 'UPDATE_OBJECT';
export const LOAD_OBJECT = 'LOAD_OBJECT';
export const REMEMBER_CHOSEN_DATA = 'REMEMBER_CHOSEN_DATA';